openapi: 3.0.0
info:
  title: CCBill API
  version: 1.0.0
paths:
  /ccbill-auth/oauth/token:
   post:
     summary: Request OAuth Token
     description: This endpoint requests an OAuth token using client credentials.
     requestBody:
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
                grant_type:
                  type: string
                  description: The type of OAuth grant being requested. For client credentials, use `client_credentials`.
                  example: client_credentials
     responses:
       '200':
         description: Successful response
         content:
           application/json:
             schema:
               type: object
               properties:
                 access_token:
                   type: string
                   description: The OAuth Bearer Token.
                 token_type:
                   type: string
                   description: The type of the token.
                 expires_in:
                   type: integer
                   description: The lifetime in seconds of the access token.
                 scope:
                   type: string
                   description: The scopes associated with the token.
       '400':
         description: Bad request
     parameters:
       - in: header
         name: Content-Type
         schema:
           type: string
         example: application/x-www-form-urlencoded
         description: Content type of the request body.
     x-code-samples:
      - lang: bash
        label: cURL (Auto-encode)
        source: |
          curl -X POST 'https://api.ccbill.com/ccbill-auth/oauth/token' \
          -i -u 'Basic Merchant_Application_ID:Secret_Key' \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'grant_type=client_credentials'
      - lang: bash
        label: cURL (Manual-encode)
        source: |
          curl -X POST \
          https://api.ccbill.com/ccbill-auth/oauth/token \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --header 'Authorization: Basic [base64_encoded_Merchant_ApplicationID:Merchant_Secret]' \
          --data-urlencode 'grant_type=client_credentials'
components: {}
