openapi: 3.0.0
info:
  title: CCBill API
  version: 1.0.0
paths:
  /ccbill-auth/oauth/token:
    post:
      summary: Request OAuth Token
      description: This endpoint requests an OAuth token using client credentials.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: client_credentials
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
        '400':
          description: Bad request
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          example: Basic Merchant_Application_ID:Secret_Key
          description: |
            Basic authentication with Merchant_Application_ID and Secret_Key.
            The value should be a Base64 encoded string of `Merchant_Application_ID:Secret_Key`.
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
          example: application/x-www-form-urlencoded
          description: Content type of the request body.

components: {}
