openapi: 3.0.0
info:
  title: CCBill API
  version: 1.0.0
paths:
  /ccbill-auth/oauth/token:
   post:
     summary: Request OAuth Token
     description: This endpoint requests an OAuth token using client credentials.
     requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
                grant_type:
                  type: string
                  description: The type of OAuth grant being requested. For client credentials, use `client_credentials`.
                  example: client_credentials
     responses:
       '200':
         description: Successful response
         content:
           application/json:
             schema:
               type: object
               properties:
                 access_token:
                   type: string
                   description: The OAuth Bearer Token.
                 token_type:
                   type: string
                   description: The type of the token.
                 expires_in:
                   type: integer
                   description: The lifetime in seconds of the access token.
                 scope:
                   type: string
                   description: The scopes associated with the token.
       '400':
         description: Bad request
     parameters:
       - in: header
         name: Authorization
         required: true
         schema:
           type: string
         example: Basic TWVyY2hhbnRfQXBwbGljYXRpb25fSUQ6U2VjcmV0X0tleQ==
         description: |
           Basic authentication with Merchant_Application_ID and Secret_Key.
           The value should be a Base64 encoded string of `Merchant_Application_ID:Secret_Key`.
       - in: header
         name: Content-Type
         required: true
         schema:
           type: string
         example: application/x-www-form-urlencoded
         description: Content type of the request body.

components: {}
