openapi: 3.0.0
info:
  title: RESTful API Endpoints
  version: 1.0.0
servers:
  - url: https://api.ccbill.com
    description: Production Server
tags:
  - name: /payment-tokens
    description: Use the `/payment-tokens` resource to create a token that identifies a user in the system. The token can be passed on to the system in a transaction request, thus enabling you to bill a customer.
  - name: /transactions
    description: |-
      Use the `/transactions` endpoint to create a charge for an existing or new customer, or to retrieve data on a charge.
      A charge can represent a transaction on a customer's billing details by a sponsor, based on a token obtained from an affiliate that identifies one of their clients.
security:
  - bearerAuth: []
paths:
  /transactions/payment-tokens/{paymentTokenId}:
    post:
      tags:
        - /transactions
      summary: Create a transaction request
      description: |-
        The POST `/transactions/payment-tokens/{paymentTokenId}` API call will create a transaction request for a customer.
        The customer is identified by a token that is obtained from an affiliate. If the token is short-lived, and this is the first billing for this customer a longer-lived token is returned.
        Supply the payment token ID as a URI parameter.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
            examples:
              30 day subscription (non-recurring):
                description: Request body for charging a token and initiating a 30 day 9.99 USD subscription which is non-recurring.
                value:
                  clientAccnum: 900123
                  clientSubacc: 0
                  initialPrice: 9.99
                  initialPeriod: 30
                  currencyCode: 840
              1 year recurring subscription:
                description: Request body for charging a token and initiating a subscription for 30 day 9.99 EUR initial period that will be renewed for 11 more times every 30 days with amount of 4.99 EUR.
                value:
                  clientAccnum: 900684
                  clientSubacc: 0
                  initialPrice: 9.99
                  initialPeriod: 30
                  recurringPrice: 4.99
                  recurringPeriod: 30
                  rebills: 11
                  currencyCode: 840
              Single billing transaction:
                description: Request body for charging a token and initiating one time transaction of 50 EUR passing a customer reference as a pass-through parameter.
                value:
                  clientAccnum: 900684
                  clientSubacc: 0
                  initialPrice: 50
                  initialPeriod: 0
                  currencyCode: 978
                  passThroughInfo:
                    - name: "customerRef"
                      value: "cus_123"
      parameters:
        - name: paymentTokenId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/vnd.mcn.transaction-service.api.v.2+json:
              schema:
                $ref: '#/components/schemas/TransactionInfoV2'
              examples: 
                Successful Transaction:
                  description: Successfully processed transaction.
                  value:
                    {
                      "declineCode": null,
                      "declineText": null,
                      "denialId": null,
                      "approved": true,
                      "paymentUniqueId": "z8Zprmki+WoAyOwj74Ei3w",
                      "sessionId": null,
                      "newPaymentTokenId": null,
                      "subscriptionId": "925014201000000206"
                    }
            application/vnd.mcn.transaction-service.api.v.1+json:
              schema:
                $ref: '#/components/schemas/TransactionInfo'
              examples: 
                Successful Transaction:
                  description: Successfully processed transaction.
                  value:
                    {
                      "declineCode": null,
                      "declineText": null,
                      "denialId": null,
                      "approved": true,
                      "paymentUniqueId": "z8Zprmki+WoAyOwj74Ei3w",
                      "sessionId": null,
                      "newPaymentTokenId": null,
                      "subscriptionId": 925014201000000206
                    }
                Failed Transaction:
                  description: Transaction that was decline due to a system error
                  value:
                    {
                      "declineCode": 27,
                      "declineText": "System Error, Please Try Again",
                      "denialId": 925013101000000100,
                      "approved": false,
                      "paymentUniqueId": null,
                      "sessionId": null,
                      "newPaymentTokenId": null,
                      "subscriptionId": null
                    }
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    PassThroughInfo:
      description: Holds a single piece of data that merchants can pass through a transaction processing flow and that will be provided back to them in the approval/denial background posts.
      type: object
      properties:
        name:
          description: Name of the pass through parameter.
          type: string
          example: "customerRef"
        value:
          description: Value of the pass through parameter
          type: string
          example: "customerOne"
      required:
        - name
        - value
    TransactionInfo:
      description: Response parameters confirm that a customer was successfully charged using a payment token.
      type: object
      properties:
        declineCode:
          description: Decline code returned in case of error.
          type: integer
          format: int64
          example: 22
        declineText:
          description: Decline message returned in case of error.
          type: string
          example: "Error contacting bank, please try again later"
        denialId:
          description: Decline ID returned in case of error.
          type: integer
          example: 925013101000000000
        approved:
          description: Approval status of the transaction.
          type: boolean
          example: true
        paymentUniqueId:
          description: Unique key connected to payment account.
          type: string
          example: z8Zprmki+WoAyOwj74Ei3w
        sessionId:
          description: Unique session ID value for transaction.
          type: string
          example: null
        subscriptionId:
          description: Subscription ID associated with the transaction.
          type: integer
          format: int64
          example: 925014201000000300
        newPaymentTokenId:
          description: New payment token for subsequent transactions.
          type: string
          example: null
    TransactionInfoV2:
      description: Response parameters confirm that a customer was successfully charged using a payment token.
      type: object
      properties:
        declineCode:
          description: Decline code returned in case of error.
          type: integer
          format: int64
          example: 22
        declineText:
          description: Decline message returned in case of error.
          type: string
          example: "Error contacting bank, please try again later"
        denialId:
          description: Decline ID returned in case of error.
          type: integer
          example: 925013101000000000
        approved:
          description: Approval status of the transaction.
          type: boolean
          example: true
        paymentUniqueId:
          description: Unique key connected to payment account.
          type: string
          example: z8Zprmki+WoAyOwj74Ei3w
        sessionId:
          description: Unique session ID value for transaction.
          type: string
          example: null
        subscriptionId:
          description: Subscription ID associated with the transaction.
          type: string
          example: 925014201000000300
        newPaymentTokenId:
          description: New payment token for subsequent transactions.
          type: string
          example: null
    TransactionRequest:
      description: Request parameters for initiating a transaction request for a customer.
      type: object
      properties:
        clientAccnum:
          description: Merchant account number.
          type: integer
          format: int32
        clientSubacc:
          description: Merchant subaccount number
          type: integer
          format: int32
        initialPrice:
          description: Price for the initial subscription period.
          type: number
          format: decimal
          example: 10
        initialPeriod:
          description: Initial subscription period after which the first recurring price will be charged.
          type: integer
          format: int64
          example: 30
        currencyCode:
          description: 3-digit currency code used for the transaction.
          type: integer
          example: 978
          format: int64
        recurringPrice:
          description: Price of the subscription renewal that will be charged regularly, after each recurring period.
          type: number
          format: decimal
          example: 5
        recurringPeriod:
          description: Renewal subscription period after which the next recurring price will be charged.
          type: integer
          format: int64
          example: 30
        rebills:
          description: Number of renewals for the recurring transaction.
          type: integer
          example: 12
          format: int64
        lifeTimeSubscription:
          description: Whether the subscription is eternal or not.
          type: boolean
          example: false
        createNewPaymentToken:
          description: Whether new payment token, that can be used for the subsequent transaction, should be generated and returned.
          type: boolean
          example: true
        passThroughInfo:
          description: Miscellaneous data that the merchant can pass in and will be provided back to them in the approval/denial background posts.
          type: array
          items:
            $ref: '#/components/schemas/PassThroughInfo'
      required:
        - clientAccnum
        - clientSubacc
        - initialPrice
        - initialPeriod
    ValidationError:
      type: object
      properties:
        field:
          description: Field in error
          type: string
        message:
          description: User friendly message
          type: string
      required:
        - field
        - message
      example:
        field: string
        message: string
    Error:
      type: object
      properties:
        id:
          pattern: ^[a-zA-Z0-9-]*$
          description: Randomly generated GUID
          type: string
        url:
          description: The RELATIVE url that has caused this error
          type: string
        generalMessage:
          description: Something human readable
          type: string
        errorCode:
          pattern: ^[0-9]*$
          description: Product defined error code
          type: string
        timestamp:
          description: Timestamp of the call
          type: string
          format: date-time
      required:
        - id
        - url
        - generalMessage
        - errorCode
        - timestamp
      example:
        id: string
        url: specific/endpoint
        generalMessage: General error message
        errorCode: "100013"
        timestamp: '2022-03-02T11:04:47.729Z'
    Error400:
      type: object
      properties:
        id:
          pattern: ^[a-zA-Z0-9-]*$
          description: Randomly generated GUID
          type: string
        url:
          description: The RELATIVE url that has caused this error
          type: string
        errors:
          description: Optional, only returned on 400 Bad Request errors for validation errors
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
        generalMessage:
          description: Something human readable
          type: string
        errorCode:
          pattern: ^[0-9]*$
          description: Product defined error code
          type: string
        timestamp:
          description: Timestamp of the call
          type: string
          format: date-time
      required:
        - id
        - url
        - generalMessage
        - errorCode
        - timestamp
      example:
        id: a98a9876-8bc87-765c-5432-4d4ef5ghij3
        url: specific/endpoint
        errors:
          - field: string
            message: string
        generalMessage: "An error occurred, please try again later."
        errorCode: "100013"
        timestamp: '2022-03-02T11:04:47.729Z'
    Error401:
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
      example:
        error: "unauthorized"
        error_description: "Full authentication is required to access this resource"
  responses:
    '400':
      description: The response failed to complete due to an invalid header/parameter in the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    '401':
      description: The response failed to complete due to authorization problem.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error401'
    '403':
      description: The response failed to complete because access to the resource is forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    '404':
      description: The response failed to complete due to an invalid resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    '405':
      description: The response failed to complete due to an invalid method of request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    '406':
      description: The response failed to complete due to an unacceptable media type in the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    '415':
      description: The response failed to complete due to an unsupported media type in the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
    '500':
      description: The response failed to complete in some way.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error400'
  parameters:
    trait_versioned_Accept:
      name: '200'
      in: header
      description: API version
      schema:
        type: string
  examples:
    PaymentTokenMerchantOnlyParamsRequired:
      summary: Required fields
      value:
        clientAccnum: 900000
        clientSubacc: 2
        customerInfo:
          $ref: '#/components/examples/CustomerInfoRequired/value'
        paymentInfo:
          creditCardPaymentInfo:
            $ref: '#/components/examples/CreditCardPaymentInfo/value'
        subscriptionId: 900000000000000000
    PaymentTokenMerchantOnlyParamsAll:
      summary: All fields
      value:
        clientAccnum: 900000
        clientSubacc: 2
        customerInfo:
          $ref: '#/components/examples/CustomerInfoAll/value'
        paymentInfo:
          creditCardPaymentInfo:
            $ref: '#/components/examples/CreditCardPaymentInfo/value'
        subscriptionId: 900000000000000000
        timeToLive: 30
        validNumberOfUse: 3
    PaymentTokenMerchantOnlyVerifyParamsRequired:
      summary: Required fields
      value:
        clientAccnum: 900000
        clientSubacc: 2
        customerInfo:
          $ref: '#/components/examples/CustomerInfoRequired/value'
        paymentInfo:
          creditCardPaymentInfo:
            $ref: '#/components/examples/CreditCardWithCvvPaymentInfo/value'
        subscriptionId: 900000000000000000
    PaymentTokenMerchantOnlyVerifyParamsAll:
      summary: All fields
      value:
        clientAccnum: 900000
        clientSubacc: 2
        customerInfo:
          $ref: '#/components/examples/CustomerInfoAll/value'
        paymentInfo:
          creditCardPaymentInfo:
            $ref: '#/components/examples/CreditCardWithCvvPaymentInfo'
        subscriptionId: 900000000000000000
        timeToLive: 30
        validNumberOfUse: 3
    CustomerInfoAll:
      value:
        customerFname: Tyler
        customerLname: Thomas
        address1: Woodland Drive
        address2: Apt 21
        city: Tempe
        state: AZ
        zipcode: '85281'
        country: US
        phoneNumber: '5555555555'
        email: tthomas@xyz.com
        ipAddress: 10.70.60.14
        browserHttpUserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
        browserHttpAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        browserHttpAcceptLanguage: en-US,en;q=0.5
        browserHttpAcceptEncoding: gzip, deflate, br
    CustomerInfoRequired:
      value:
        customerFname: Tyler
        customerLname: Thomas
        zipcode: '85281'
        country: US
        email: tthomas@xyz.com
        ipAddress: 10.70.60.14
    CreditCardWithCvvPaymentInfo:
      value:
        cardNum: '4473707989493598'
        nameOnCard: Tyler Thomas
        expMonth: '04'
        expYear: '2026'
        cvv2: '123'
    CreditCardPaymentInfo:
      value:
        cardNum: '4473707989493598'
        nameOnCard: Tyler Thomas
        expMonth: '04'
        expYear: '2026'
  requestBodies: {}
  headers: {}
  links: {}
  callbacks: {}